spring:
  application:
    name: springcloud-zuul
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-service:
      path: /api/service/**
      serviceId: springcloud-service
    api-feign:
      path: /api/feign/**
      serviceId: springcloud-feign
