spring:
  application:
    name: springcloud-eureka
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

#Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
